name: prueba_flutter_developer_magis
description: "Aplicación de películas usando la API de TMDb para prueba técnica."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Gestión de estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  
  # Networking
  dio: ^5.4.0
  http: ^1.1.0
  
  # Almacenamiento local
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # UI
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utilidades
  intl: ^0.19.0
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  
  # Reproductor de video
  youtube_player_flutter: 9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  build_runner: ^2.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/animations/
    - .env
